# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-05-11 23:02
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('first_app', '0003_user_following'),
    ]

    operations = [
        migrations.CreateModel(
            name='Following',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.RemoveField(
            model_name='user',
            name='following',
        ),
        migrations.AddField(
            model_name='following',
            name='belongs',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='following', to='first_app.User'),
        ),
        migrations.AddField(
            model_name='following',
            name='follow',
            field=models.ManyToManyField(related_name='followers', to='first_app.User'),
        ),
    ]
